cask_args appdir: '/Applications'

brew "ast-grep"
brew "eza"
brew "fish"
brew "fzf"
brew "git-absorb"
brew "git-delta"
brew "go"
brew "htop"
brew "lazygit"
brew "mise"
brew "neovim"
brew "podman"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "wget"
brew "zoxide"
brew "zoxide"
cask "amethyst"
cask "dbeaver-community"
cask "ghostty"
cask "keycastr"
cask "monitorcontrol"
cask "obsidian"
cask "raycast"
